image: node:18-slim

stages:
  - lint
  - test
  - build
  - package

cache:
  paths:
    - node_modules/

lint:
  stage: lint
  script:
    - npm ci
    - npm run lint
  allow_failure: false

test-unit:
  stage: test
  script:
    - npm ci
    - npm run test
  artifacts:
    when: always

test-integration:
  stage: test
  variables:
    DISPLAY: ':99.0'
  script:
    - apt-get update
    - apt-get install -y libglib2.0-0 libgtk-3-0 libnss3 libxss1 libasound2 libsecret-1-0
    - npm ci
    - echo $DISPLAY
    - /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm run test

build_project:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - out
    expire_in: 1 hour

package:
  stage: package
  script:
    - npm ci
    - npx vsce package
  artifacts:
    paths:
      - '*.vsix'
    expire_in: 1 year
  only:
    - tags
